-- require("neorg").setup({
-- 	load = {
-- 		["core.defaults"] = {}, -- Loads default behaviour
-- 		["core.concealer"] = {}, -- Adds pretty icons to your documents
-- 		["core.dirman"] = { -- Manages Neorg workspaces
-- 			config = {
-- 				workspaces = {
-- 					school = "~/Desktop/School/Notes",
-- 				},
-- 				default_workspace = "school",
-- 			},
-- 		},
-- 	},
-- })
